# Computational Illustration for Chapter 15
# The Complexity of Sparse Recovery

In [1]:
import numpy as np
from numpy import linalg as LA
from scipy import linalg
from scipy.optimize import linprog

In [2]:
## generate a s-sparse vector and its first 2s Fourier observations
# select problem sizes
N = 500
s = 10
m = 2*s
# create the sparse vector x to be recovered
x = np.zeros(N)
aux = np.random.permutation(N)
supp_ori = aux[:s]
supp_ori.sort()
x[supp_ori] = np.random.normal(0,1,s)
# produce the observation vector y made of 2s Fourier coefficients 
xhat = np.fft.fft(x)
y_exact = xhat[:m]
# as well as a noisy version
noise = 1e-5*np.random.normal(0,1,m)
y_noisy = y_exact+noise

## Sparse recovery via Prony's method seems to be successful...

In [3]:
phat = np.zeros(N, dtype=np.cfloat)
phat[0] = 1
M = linalg.toeplitz(y_exact[s-1:2*s-1], y_exact[s-1::-1])
phat[1:s+1] = -linalg.solve(M,y_exact[s:2*s])
p = np.fft.ifft(phat)
idx = np.argsort(abs(p))
supp_exact = idx[0:s]
supp_exact.sort()
print('In the exact case, the original and recovered supports agree:')
print(supp_ori)
print(supp_exact)

In the exact case, the original and recovered supports agree:
[  6  44  61  77  95 219 266 282 294 372]
[  6  44  61  77  95 219 266 282 294 372]


## But it is not robust to observation errors with only m=2s

In [4]:
phat = np.zeros(N, dtype=np.cfloat)
phat[0] = 1
M = linalg.toeplitz(y_noisy[s-1:2*s-1], y_noisy[s-1::-1])
phat[1:s+1] = -linalg.solve(M,y_noisy[s:2*s])
p = np.fft.ifft(phat)
idx = np.argsort(abs(p))
supp_noisy = idx[0:s]
supp_noisy.sort()
print('In the noisy case, the original and recovered supports do not agree anymore:')
print(supp_ori)
print(supp_noisy)

In the noisy case, the original and recovered supports do not agree anymore:
[  6  44  61  77  95 219 266 282 294 372]
[  6  44  62  77  95 219 266 282 294 372]


In [5]:
## The outputted vectors do not agree either
F = linalg.dft(N)    # the full discrete Fourier matrix
A = F[:2*s,:]        # the submatrix for the first 2s Fourier coefficients
x_exact = np.zeros(N, dtype=np.cfloat)
x_exact[supp_exact] = linalg.solve(A[:s,supp_exact],y_exact[:s])
rel_error_exact = LA.norm(x-x_exact)/LA.norm(x)
x_noisy = np.zeros(N, dtype=np.cfloat)
x_noisy[supp_noisy] = linalg.solve(A[:s,supp_noisy],y_noisy[:s])
rel_error_noisy = LA.norm(x-x_noisy)/LA.norm(x)
print('Recovery from exact observations is quite successful: relative L2-error = {}.'.format(rel_error_exact))
print('Recovery from inexact observations is not successful: relative L2-error = {}.'.format(rel_error_noisy))

Recovery from exact observations is quite successful: relative L2-error = 3.2685480453828115e-13.
Recovery from inexact observations is not successful: relative L2-error = 0.25916335609447555.


## In contrast, recovery via L1-minimization is stable (with more observations, of course)

In [7]:
m = 4*s
A = F[:m,:] 
y_exact = A@x
y_noisy = y_exact+1e-5*np.random.normal(0,1,m)
obj= np.ones(2*N)
lhs_eq = np.append(np.append(A.real, -A.real, axis=1), np.append(A.imag, -A.imag, axis=1), axis=0)
rhs_eq_exact = np.append(y_exact.real, y_exact.imag, axis=0)
rhs_eq_noisy = np.append(y_noisy.real, y_noisy.imag, axis=0)
bnd = [(0, np.inf) for _ in range(2*N)]
opt_exact = linprog(c=obj, A_eq=lhs_eq, b_eq=rhs_eq_exact, bounds=bnd, method="interior-point")
xstar_exact = opt_exact.x[:N]-opt_exact.x[N:]
rel_error_exact = LA.norm(x-xstar_exact)/LA.norm(x)   
opt_noisy = linprog(c=obj, A_eq=lhs_eq, b_eq=rhs_eq_noisy, bounds=bnd, method="interior-point")
xstar_noisy = opt_noisy.x[:N]-opt_noisy.x[N:]
rel_error_noisy = LA.norm(x-xstar_noisy)/LA.norm(x)    
print('Recovery from exact observations is quite successful: relative L2-error = {}.'.format(rel_error_exact))
print('Recovery from inexact observations is not bad either: relative L2-error = {}.'.format(rel_error_noisy))

Recovery from exact observations is quite successful: relative L2-error = 1.154916540329676e-10.
Recovery from inexact observations is not bad either: relative L2-error = 3.2852828248803705e-05.
